version: "2.4"
services:
  task5:
    container_name: task5
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7171:7171
    volumes:
      - ./code:/code:ro
    read_only: true
    pids_limit: 256
    mem_limit: 512M
    cpus: 0.25