version: "3.7"
services:
  backend:
    container_name: task4
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 7070:7070
    volumes:
      - ./code:/code:rw
